language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update >/dev/null
  - sudo apt-get -q install libprotobuf-c0-dev protobuf-c-compiler
  - sudo pip install pytz python-dateutil
  - wget http://softlayer-ams.dl.sourceforge.net/project/check/check/0.9.14/check-0.9.14.tar.gz
  - tar zxf check-0.9.14.tar.gz
  - cd check-0.9.14
  - ./configure >/dev/null
  - make >/dev/null
  - sudo make install >/dev/null

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ctest
  - python -m unittest discover ../rrtimetable/rrtimetable "*_tests.py"

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "sInCQux5fHnN+3Ai4t1SaKjarjbw7trh52lP2SzJz/Oja/nD6vLbPpEV0sdkavQzT98DXaVOYnhagmXmXEK6xnbh6R1+Rl0x0LRWxbALBQf+vM6QbX9PWwIF42RgwNdI5d/9WupyGazPi7l5TU9My1uocvxtFcFs32pPhQ0lqmk="

addons:
  coverity_scan:
    project:
      name: "bliksemlabs/rrrr"
      description: "RRRR rapid real-time routing"
    notification_email: coverity@bliksemlabs.org
    build_command_prepend: "rm -r build; mkdir build; cd build ; cmake .."
    build_command: "make"
    branch_pattern: ansi
